"""notify-alert sink configuration for `bastion setup` (the L6 alert-destinations step).

The L6 alerter (`notify-alert`) sources /etc/bastion/notify-alert.conf for its sinks: a public
ntfy topic + external email (which receive ONLY the degraded-only template — no arch detail) and
an OPTIONAL internal ntfy reachable over an operator-controlled network (full detail). Those
values — the topic (a capability URL), the email (secret), the internal URL/auth (secret) — are
operator/secret material, so they are NEVER committed and NEVER installed by the L6 module; the setup
wizard renders the real conf from operator input, the same pattern as the edge-ai claude.env.

This module is the pure / IO-thin half (mirrors ai_backend.py): it DETECTS an existing conf so a
reinstall reuses it, RENDERS the shell-sourceable conf, and WRITES it chmod 600. All IO goes
through `System`, so it is fully testable with a fake System — no host access, no network.
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from ..system import System

ALERT_CONF = "/etc/bastion/notify-alert.conf"


@dataclass(frozen=True)
class Field:
    key: str          # shell var name notify-alert sources
    prompt: str       # wizard question
    default: str      # proposed default ("" = blank disables the sink)
    secret: bool      # hidden input (auth token)


# Prompt order mirrors the annotated example. NTFY_SERVER is only asked when a topic is set.
FIELDS: tuple[Field, ...] = (
    Field("NTFY_TOPIC", "Public ntfy topic (degraded-only alerts; blank = disable ntfy)", "", False),
    Field("NTFY_SERVER", "ntfy server", "https://ntfy.sh", False),
    Field("ALERT_EMAIL", "Alert email (degraded-only; blank = disable email)", "", False),
    Field("INTERNAL_NTFY_URL",
          "Internal ntfy URL (full detail, operator network only; blank = journal only)", "", False),
    Field("INTERNAL_NTFY_AUTH", "Internal ntfy auth header (blank = none)", "", True),
)


def conf_present(sys: System, path: str = ALERT_CONF) -> bool:
    """True when a notify-alert.conf already exists (reinstall reuse — don't re-prompt/overwrite)."""
    return sys.exists(path)


def _shell_quote(value: str) -> str:
    """Single-quote a value for safe shell sourcing (an auth header may contain $, spaces, etc.)."""
    return "'" + value.replace("'", "'\\''") + "'"


def render_conf(values: dict[str, str]) -> str:
    """Render the shell-sourceable notify-alert.conf from operator values. Only keys in FIELDS are
    emitted; a missing/blank value renders an empty (disabled) sink."""
    lines = [
        "# bastion notify-alert config — generated by `bastion setup`. chmod 600, root-only.",
        "# NEVER commit this file: the topic/email/internal URL are installation-specific values.",
        "# Tiered alerting: external sinks (ntfy topic + email) get the degraded-only template;",
        "# full detail goes only to the local journal and the internal ntfy.",
    ]
    for f in FIELDS:
        lines.append(f"{f.key}={_shell_quote(values.get(f.key, '') or '')}")
    return "\n".join(lines) + "\n"


def apply_alerts(sys: System, values: dict[str, str], *, path: str = ALERT_CONF) -> str:
    """Write notify-alert.conf chmod 600 (root-prefixed via ``sys.path`` so --root staging stays
    contained). Returns the logical (un-rooted) path written."""
    dest = sys.path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(dest, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as fh:
        fh.write(render_conf(values))
    os.chmod(dest, 0o600)
    return path


def has_any_sink(values: dict[str, str]) -> bool:
    """True if the operator supplied at least one real sink (topic/email/internal URL). An all-blank
    conf is pointless — notify-alert already no-ops on an absent conf — so the wizard skips writing."""
    return any((values.get(k) or "").strip()
               for k in ("NTFY_TOPIC", "ALERT_EMAIL", "INTERNAL_NTFY_URL"))
